name: publish-docker
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build the  Docker image
        uses: actions/checkout@v2
        run: |
             docker build -t ghcr.io/hopr-framework/docker-demo:latest -f docker_image/ubuntu20_hoprexec.dockerfile docker_image/.

#       docker push ghcr.io/hopr-framework/docker-demo:latest
