name: publish-docker
on: [push]
jobs:
publish-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the  Docker image
run: |
       docker build -t ghcr.io/hopr-framework/docker-demo:latest -f docker_image/ubuntu20_hoprexec.dockerfile docker_image/.
       docker push ghcr.io/hopr-framework/docker-demo:latest
